#!/usr/bin/env bash
#
# Create a new autogenerated migration with a proper sequential prefix.
#
# Usage:
#   ./backend/scripts/new_migration.sh "add user avatar"
#
# This will:
#   1. Find the next NNN prefix (e.g. 002 if 001 exists)
#   2. Run alembic revision --autogenerate with that prefix
#   3. Rename the file to use the NNN prefix
#
set -euo pipefail

if [ $# -eq 0 ]; then
    echo "Usage: $0 <description>"
    echo "Example: $0 'add user avatar column'"
    exit 1
fi

DESCRIPTION="$1"
VERSIONS_DIR="backend/migrations/versions"

# Find the highest existing NNN prefix
LAST_NUM=$(ls "$VERSIONS_DIR"/*.py 2>/dev/null \
    | xargs -I{} basename {} \
    | grep -oP '^\d{3}' \
    | sort -n \
    | tail -1)

if [ -z "$LAST_NUM" ]; then
    NEXT_NUM="001"
else
    NEXT_NUM=$(printf "%03d" $((10#$LAST_NUM + 1)))
fi

# Convert description to snake_case slug
SLUG=$(echo "$DESCRIPTION" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | tr -cd 'a-z0-9_')

REVISION_ID="${NEXT_NUM}_${SLUG}"

echo "Creating migration: $REVISION_ID"

# Generate the autogenerated migration
alembic -c backend/alembic.ini revision \
    --autogenerate \
    --rev-id "$REVISION_ID" \
    -m "$DESCRIPTION"

echo ""
echo "Migration created. Next steps:"
echo "  1. Review the generated file in $VERSIONS_DIR/"
echo "  2. Verify the upgrade() and downgrade() are correct"
echo "  3. Test: alembic -c backend/alembic.ini upgrade head"
echo "  4. Test: alembic -c backend/alembic.ini downgrade -1"
echo "  5. Test: alembic -c backend/alembic.ini upgrade head"
