import { useMemo } from 'react';
import { useTasks } from '../../hooks';
import type { Project } from '../../types';

interface ArtifactBrowserProps {
  projectId: string;
  project: Project;
}

export function ArtifactBrowser({ projectId, project }: ArtifactBrowserProps) {
  const { tasks, isLoading, error } = useTasks(projectId);

  const recentChanges = useMemo(() => {
    return tasks
      .filter((task) => task.module_path || task.git_branch || task.pr_url)
      .sort((a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime())
      .slice(0, 30);
  }, [tasks]);

  const moduleGroups = useMemo(() => {
    const map = new Map<string, number>();
    for (const task of recentChanges) {
      const key = task.module_path || '(unspecified)';
      map.set(key, (map.get(key) || 0) + 1);
    }
    return Array.from(map.entries()).sort((a, b) => b[1] - a[1]);
  }, [recentChanges]);

  return (
    <div className="h-full bg-white border border-gray-200 rounded-lg overflow-hidden">
      <div className="px-4 py-3 border-b border-gray-200">
        <h2 className="text-lg font-semibold text-gray-900">Artifact & Knowledge Browser</h2>
        <p className="text-sm text-gray-500">Recent changes, branches/PRs, and project context</p>
      </div>

      <div className="h-[calc(100%-68px)] overflow-y-auto p-4 space-y-6">
        {isLoading && <p className="text-sm text-gray-500">Loading artifacts...</p>}
        {error && <p className="text-sm text-red-600">{error.message}</p>}

        <section>
          <h3 className="text-sm font-semibold text-gray-900 mb-2">Recent Changes</h3>
          {recentChanges.length === 0 ? (
            <p className="text-sm text-gray-500">No code artifacts yet. Tasks with module paths, branches, or PRs will appear here.</p>
          ) : (
            <ul className="space-y-2">
              {recentChanges.map((task) => (
                <li key={task.id} className="border border-gray-200 rounded p-3">
                  <p className="text-sm font-medium text-gray-900">{task.title}</p>
                  <p className="text-xs text-gray-600 mt-1">
                    Module: {task.module_path || 'n/a'} · Status: {task.status}
                  </p>
                  <div className="mt-2 flex items-center gap-2 text-xs">
                    {task.git_branch && (
                      <span className="px-2 py-1 rounded bg-blue-100 text-blue-700">
                        {task.git_branch}
                      </span>
                    )}
                    {task.pr_url && (
                      <a
                        href={task.pr_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="px-2 py-1 rounded bg-purple-100 text-purple-700 hover:bg-purple-200"
                      >
                        View PR
                      </a>
                    )}
                  </div>
                </li>
              ))}
            </ul>
          )}
        </section>

        <section>
          <h3 className="text-sm font-semibold text-gray-900 mb-2">Diff View (Task-Scoped)</h3>
          {recentChanges.length === 0 ? (
            <p className="text-sm text-gray-500">No pending diffs. PR links will appear in recent changes once generated by agents.</p>
          ) : (
            <div className="rounded border border-gray-200 bg-gray-50 p-3">
              <p className="text-xs text-gray-600">
                This view summarizes task-level code changes. Open linked PRs for inline diffs and review comments.
              </p>
            </div>
          )}
        </section>

        <section>
          <h3 className="text-sm font-semibold text-gray-900 mb-2">Knowledge Context</h3>
          <div className="grid gap-2">
            <div className="rounded border border-gray-200 p-3">
              <p className="text-xs uppercase text-gray-500">Spec Repository Path</p>
              <p className="text-sm text-gray-800 font-mono break-all">{project.spec_repo_path}</p>
            </div>
            <div className="rounded border border-gray-200 p-3">
              <p className="text-xs uppercase text-gray-500">Code Repository Path</p>
              <p className="text-sm text-gray-800 font-mono break-all">{project.code_repo_path}</p>
            </div>
            <div className="rounded border border-gray-200 p-3">
              <p className="text-xs uppercase text-gray-500">Tracked Modules</p>
              {moduleGroups.length === 0 ? (
                <p className="text-sm text-gray-500">No modules tracked yet.</p>
              ) : (
                <ul className="mt-2 space-y-1">
                  {moduleGroups.map(([modulePath, count]) => (
                    <li key={modulePath} className="text-sm text-gray-700">
                      {modulePath} <span className="text-gray-500">({count})</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}

export default ArtifactBrowser;
